-- Otorgar permisos al usuario carlos
GRANT ALL PRIVILEGES ON DATABASE banco_peru TO carlos;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO carlos;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO carlos;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO carlos;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO carlos;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO carlos;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO carlos;
GRANT ALL PRIVILEGES ON SCHEMA public TO carlos;
